# Generated by Django 4.1.3 on 2023-02-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AadharDB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhar',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
