# Generated by Django 4.1.3 on 2023-02-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AadharDB', '0002_aadhar_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhar',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/% Y/% m'),
        ),
    ]
